# Generated by Django 5.2.5 on 2025-11-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_orderdetail_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
